; PlatformIO Project Configuration File
; NightKite Link - M5Stack Cardputer handheld CLI/macro terminal

[platformio]
default_envs = cardputer

[env:cardputer]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.03/platform-espressif32.zip
board = m5stack-stamps3
framework = arduino

monitor_speed = 115200
monitor_filters =
    esp32_exception_decoder

upload_speed = 1500000
extra_scripts =
    pre:scripts/patch_m5cardputer.py

build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=0
    -D CORE_DEBUG_LEVEL=1
    -D LV_CONF_SKIP
    -D NIGHTKITE_USB_HOST=1

lib_deps =
    m5stack/M5Unified
    m5stack/M5GFX
    m5stack/M5Cardputer
    lvgl/lvgl@^8.4.0
    https://github.com/bertmelis/USBHostSerial.git
